version: '2'
services:
  db:
    image: hypriot/rpi-mysql:latest
    volumes:
      - "/docker_nfs/owncloud-sql/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud 
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
   
  owncloud:
    depends_on:
      - db
    image: patrckbrs/owncloud-sql:latest
    volumes:
      - "/docker_nfs/owncloud-sql/config:/var/www/owncloud/config"
      - "/docker_nfs/owncloud-sql/data:/var/www/owncloud/data"
    links:
      - db
    ports:
      - "3306:3306"
      - "8080:80"
      - "1443:443"
    restart: always
